FROM node:alpine

WORKDIR '/app'

COPY package.json .
RUN npm install

COPY . .
#leave copy as ref for future

CMD ["npm", "run", "start"]

#docker run -it -p 3000:3000 CONTAINER_ID

#        web:
#           stdin_open: true
#