FROM node:alpine
# as builder i snot needed for AWS

WORKDIR '/app'

COPY package.json

RUN npm install

COPY . .

RUN npm run build


#/app/build <-- all build stuff

FROM nginx
# --from-builder
COPY --from=0 /app/build /usr/share/nginx/html

